### ISSUE TITLE
Return type of LinearRing.difference() varies based on implementation internals

### ISSUE THREAD

**Issue by jpmaterial** [Toblerity/Shapely#771] opened 2019-09-06 14:03 UTC
## Expected behavior and actual behavior.

EB: When subtracting from a LinearRing, the result type should not depend on where on the ring the difference is applied. It is a ring after all and that it internally is a variant of linear array is only an implementation detail that should be abstracted away.

AB: Depending on where you substract, you either get a LineString or a MultiLineString. This makes for overly complex algorithms. You should not have to concern yourself with where the "wrap-around" of the LinearRing is. Some further operations might be possible with both LineString and MultiLineString, but others are not. Also, geometries should always be represented by the simplest type that can represent them.

## Steps to reproduce the problem.
(From the Python console)
<pre>
>>> LR=LinearRing([(1,0),(2,0),(2,1),(1,1)])
>>> DL=LineString([(0,1),(3,1)])
>>> diff=LR.difference(DL)
>>> type(diff)
class 'shapely.geometry.multilinestring.MultiLineString'
>>> DL_2=LineString([(0,0),(3,0)])
>>> diff_2=LR.difference(DL_2)
>>> type(diff_2)
class 'shapely.geometry.linestring.LineString'
>>> list(diff.geoms[0].coords)
[(1.0, 0.0), (2.0, 0.0), (2.0, 1.0)]
>>> list(diff.geoms[1].coords)
[(1.0, 1.0), (1.0, 0.0)]
>>> list(diff_2.coords)
[(2.0, 0.0), (2.0, 1.0), (1.0, 1.0), (1.0, 0.0)]
</pre>

## Operating system

Windows 10

## Shapely version and provenance

1.7a2 cloned from github, installed with setup.py develop

**Comment by dbaston** [comment] 2019-09-19 20:12
Confirmed same behavior in JTS master @dr-jts

**Comment by dr-jts** [comment] 2019-09-19 20:32
Well, maybe.  The semantic chosen in JTS was to preserve all noding in the output of overlay operations.  The reasons are:

* efficiency - avoid having to do extra graph traversing if not needed by client
* preserving information - Noding constitutes extra information which might be desired by the client

If merged linework is desired the `LineMerger` class (in JTS) can be used to create this _post facto_. 

Another option would be to provide a flag to the Overlay algorithm to merge linework.
Or, perhaps it does make sense to merge linework if the input is a LinearRing.  (This gets more complicated for mixed inputs, so probably only a single LinearRing would be handled).

**Comment by sgillies** [comment] 2021-02-27 00:03
Let's reopen this if there is a problem in GEOS 3.9.

**Closed by sgillies** 2021-02-27 00:03 UTC
Labels: geos, upstream bug

**Comment by jorisvandenbossche** [comment] 2021-02-27 08:12
With GEOS 3.9.1, I still see the same difference between both cases

```
In [1]: import shapely

In [2]: shapely.geos.geos_version_string
Out[2]: '3.9.1dev-CAPI-1.14.1'

In [5]: from shapely.geometry import LinearRing, LineString

In [6]: LR = LinearRing([(1,0),(2,0),(2,1),(1,1)])
   ...: DL = LineString([(0,1),(3,1)])
   ...: diff = LR.difference(DL)

In [7]: type(diff)
Out[7]: shapely.geometry.multilinestring.MultiLineString

In [8]: diff.wkt
Out[8]: 'MULTILINESTRING ((1 0, 2 0, 2 1), (1 1, 1 0))'

In [9]: DL_2 = LineString([(0,0),(3,0)])
   ...: diff_2 = LR.difference(DL_2)

In [10]: type(diff_2)
Out[10]: shapely.geometry.linestring.LineString

In [11]: diff_2.wkt
Out[11]: 'LINESTRING (2 0, 2 1, 1 1, 1 0)'
```

(but I don't think it is worth keeping this open for. If it's worth looking into, it's a GEOS issue in any case)

**Comment by dr-jts** [comment] 2021-02-27 16:08
OverlayNG GEOS 3.9 intentionally reproduces the previous overlay semantics, to avoid affecting clients and tests relying on behaviour.

As mentioned about, linear output can be merged together if required.   (And this could be only invoked on LinearRing inputs, if that selectivity is required).
