### ISSUE TITLE
dll load failed: shapely.vectorized

### ISSUE THREAD

**Issue by ccornchip** [Toblerity/Shapely#1184] opened 2021-08-24 20:57 UTC
## Expected behavior and actual behavior.

I'm trying to install shapely on Windows 10.
I have pip version 21.2.4
I have python version 3.6.8

In powershell (or cmd) I type
`pip install shapely==1.7.1`
all seems ok.
Then when I try to import, e.g.
`python -c "import shapely.vectorized"`
I get:
`ImportError: DLL load failed`

I tried inside and outside a venv, same results both ways.

I fired up docker and tried in a linux container and it's ok.  It seems to be just a windows issue.
Also, `import shapely` works fine, it seems to be just `shapely.vectorized` that has the problem.

## Steps to reproduce the problem.
```
pip install shapely==1.7.1
python3 -c "import shapely.vectorized"
```
## Operating system

Windows 10

## Shapely version and provenance

pip install shapely==1.7.1

I also tried with the whl files provided, but same problem

**Comment by mwtoews** [comment] 2021-08-25 02:04
I can confirm this behavior with Python 3.7 x64.

But also try this:
```
pip install numpy
python -c "from shapely import speedups; import shapely.vectorized"
```
any error?

I still see the same error with `python -c "import shapely.vectorized"`. A fix would be to reorder imports somewhere.

**Comment by ccornchip** [comment] 2021-08-25 06:51
Thank you! Importing speedups beforehand works. It doesn't seem very clean, but it'll see me through while the problem gets (hopefully) fixed.

**Comment by sgillies** [comment] 2021-09-30 00:23
@jorisvandenbossche sorry about the late response. I agree, that although speedups has been intended to be a low-level module, importing it in the vectorized module does feel like dodging the deeper problems. I'm not sure what the right solution is.

**Comment by jorisvandenbossche** [comment] 2021-09-30 10:31
> I agree ... importing it in the vectorized module does feel like dodging the deeper problems. I'm not sure what the right solution is.

On the other hand, it's only a short term work-around, as the speedup module will be removed for 2.0 anyway. So maybe that's "good enough" then for now?

**Comment by jorisvandenbossche** [comment] 2021-09-30 11:20
I tried adding the import in #1191, in case we want this work-around, but it doesn't seem to have fixed the issue on Appveyor ..

**Comment by sgillies** [comment] 2021-10-03 22:34
Python 3.8 and 3.9 ... could this be a need to use https://docs.python.org/3/library/os.html#os.add_dll_directory ?

**Comment by sgillies** [comment] 2021-10-04 14:17
Got it. I'll merge #1197 when the builds pass and close this issue.

**Closed** 2021-10-04 15:21 UTC
Labels: bug

**Comment by jorisvandenbossche** [comment] 2021-10-04 18:50
Ah, good find!

**Comment by sgillies** [comment] 2021-10-04 20:20
@jorisvandenbossche the problem was hiding in the missing details of Python's vague error message.
