### ISSUE TITLE
pip install shapely fails in Windows

### ISSUE THREAD

**Issue by Cloudmersive** [Toblerity/Shapely#724] opened 2019-06-02 17:01 UTC
A huge number of articles are online about trying to get Shapely to install on Windows, e.g.:

https://deparkes.co.uk/2015/01/29/install-shapely-on-anaconda/

Can we simply publish the relevant wheels to pip so that this works?

**Comment by snorfalorpagus** [comment] 2019-06-03 08:18
Duplicate of #367

**Closed by snorfalorpagus** 2019-06-03 08:18 UTC
