### ISSUE TITLE
Intersection of certain GeometryCollections segfaults

### ISSUE THREAD

**Issue by asgeirrr** [Toblerity/Shapely#860] opened 2020-03-04 15:36 UTC
## Expected behavior and actual behavior.

`intersection()` method segfaults when intersecting a Polygon with some GeometryCollection. Converting the collection into a MultiPolygon fixes the problem.

I tried coming up with arbitrary GeometryCollections but I couldn't reproduce the error except for the example below.

## Steps to reproduce the problem.

```
from shapely.geometry import shape
from shapely.ops import unary_union


polygon = shape({
    "type": "Polygon",
    "coordinates": [[
        [132.55004882812503, 34.2288353852272],
        [132.55004882812503, 34.22997081127308],
        [132.55142211914062, 34.22997081127308],
        [132.55142211914062, 34.2288353852272],
        [132.55004882812503, 34.2288353852272]
    ]]
})

collection = shape({
    "type": "GeometryCollection",
    "geometries": [{
        "type": "MultiPolygon",
        "coordinates": [
            [[
                [132.55004882812503, 34.22993173063148],
                [132.55004882812503, 34.22997081127308],
                [132.5500874053658, 34.22997081127308],
                [132.55004882812503, 34.22993173063148]
            ]],
            [[
                [132.5501380995388, 34.22997081127308],
                [132.55180084417634, 34.22997081127308],
                [132.55180084417634, 34.228694170127646],
                [132.5501380995388, 34.22997081127308]
            ]]
        ]
    }]
})

# Intersecting this particular collection fails
polygon.intersection(collection)

# Converting the collection into a multipolygon circumvents the segfault and
# works as expected
multipolygon = unary_union(collection)
polygon.intersection(multipolygon)
```
## Operating system

Reproduced on MacOS 10.15 Catalina and an up-to-date Manjaro Linux installation.

## Shapely version and provenance

Fails on both 1.6.4.post2 and 1.7.0 installed via pip in a clean virtualenv.

Thanks for any information on the problem or a fix.

**Comment by asgeirrr** [comment] 2020-03-04 16:08
I've stumbled on another example:

```python
from shapely.geometry import shape
from shapely.ops import unary_union


polygon = shape({
    "type": "Polygon",
    "coordinates": [[
        [1.9280898571014473, 41.26269360649398],
        [1.9280898571014473, 41.267195716664716],
        [1.934056631049079, 41.267195716664716],
        [1.934056631049079, 41.26269360649398],
        [1.9280898571014473, 41.26269360649398]
    ]]
})

collection = shape({
    "type": "GeometryCollection",
    "geometries": [{
        "type": "MultiPolygon",
        "coordinates": [
            [[
                [1.933593750000014, 41.26954950284258],
                [1.9226074218749893, 41.26954950284258],
                [1.9226074218749893, 41.26129149391986],
                [1.933593750000014, 41.26129149391986],
                [1.933593750000014, 41.26954950284258]
            ]],
            [[
                [1.9225859642028806, 41.26033982031611],
                [1.9335937499999998, 41.26033982031611],
                [1.9335937499999998, 41.261130194285094],
                [1.9225859642028806, 41.261130194285094],
                [1.9225859642028806, 41.26033982031611]
            ]]
        ]
    }]
})

# Intersecting this particular collection fails
polygon.intersection(collection)

# Converting the collection into a multipolygon circumvents the segfault and
# works as expected
multipolygon = unary_union(collection)

**Comment by sgillies** [comment] 2020-03-04 16:27
I confirmed your report using your first example with a 1.7.0 manylinux1 wheel and python 3.7. If use shapely 1.7.0 installed with the `--no-binary shapely` option, using the GEOS 3.6.2 installed on my computer, I cannot produce the segmentation fault. There are two workarounds, one in code (thanks for that) and one in installation. I'm interested in solving this for the binary wheels, for sure.

**Comment by asgeirrr** [comment] 2020-03-05 08:57
Perhaps it's connected to the version of GEOS. Manjaro Linux has version 3.8.0 in the repositories and installing shapely with `--no-binary` option does not help. However, it works in Ubuntu 18.04.3 LTS Bionic (tested in a Docker image) which has GEOS in version 3.6.2.

**Comment by sgillies** [comment] 2020-03-05 15:53
If you're able to succeed with GEOS 3.6.2 but not 3.8.0, then this could be a GEOS defect. I didn't find any existing issues in the GEOS tracker, so I think this is a newly discovered bug.

**Comment by dr-jts** [comment] 2020-11-04 16:47
As mentioned on the related GEOS issue, strictly speaking `GeometryCollections` are not supported by overlay operations.  In particular, collections containing overlapping polygons can't be processed.

So Shapely should probably detect this kind of input and error out appropriately.  If it wants to be more lenient, it could transform homogeneous collections of lines and points into Multi geometries and process those.  And even further, it could run a unary union on arbitrary collections and then process those in some way (although it gets complicated deciding how to process heterogeneous collections via various overlay ops, so may not be worth bothering).

**Comment by sgillies** [comment] 2020-11-05 15:39
Thanks for the comments @dr-jts !

I think we'll take the approach of raising an exception for GeometryCollection inputs and letting users make transformations.

**Comment by jorisvandenbossche** [comment] 2021-09-08 08:54
@dr-jts is your comment still correct for the new OverlayNG in GEOS 3.9.0 as well? (which was released after your comment, although already in active development / in GEOS master at that time). I suppose yes?

I am personally a bit wary of generally raising an exception for all GeometryCollection inputs. I think that might give lots of errors also in cases where the result was actually fine (eg for geopandas users with arrays of geometries, you might have introduced some geometry collections with another operation). If we go this route, we should at least first warn about it I think.

I fully agree we should prevent users to see a segfault crash, but trying the specific example of a non-supported case (collections containing overlapping polygons), the latest GEOS release actually already raises an error about it itself (i.e. and thus not crashing), which we propagate to the user:

```python
from shapely.geometry import box, GeometryCollection

polygon = box(1, 1, 3, 3)
# collection with two overlapping polygons
collection = GeometryCollection([box(0, 0, 2, 2), box(1, 1, 4, 4)])

>>> polygon.intersection(collection)
TopologyException: side location conflict at 1 2
---------------------------------------------------------------------------
TopologicalError                          Traceback (most recent call last)
...
TopologicalError: This operation could not be performed. Reason: unknown
``` 

So *if* GEOS generally raises errors (instead of crashing) for cases it doesn't support (but does it do this generally?), this might already be good enough without specific checks needed in Shapely?

**Comment by dr-jts** [comment] 2021-09-08 15:41
> @dr-jts is your comment still correct for the new OverlayNG in GEOS 3.9.0 as well? (which was released after your comment, although already in active development / in GEOS master at that time). I suppose yes?

Yes, the comment about "strictly speaking GeometryCollections are not handled" still applies to OverlayNG.

OverlayNG will process some GeometryCollections, but with the following limitations:
* heterogeneous (mixed) collections are not supported (they throw an `IllegalArgumentException`)
* collections containing overlapping polygons will probably throw an error (as you note below)
* the semantics for GeometryCollections hasn't been formally defined.  At the moment they just have the same behaviour as typed collections, but that might change in the future to something slightly different

> I am personally a bit wary of generally raising an exception for all GeometryCollection inputs. I think that might give lots of errors also in cases where the result was actually fine (eg for geopandas users with arrays of geometries, you might have introduced some geometry collections with another operation). If we go this route, we should at least first warn about it I think.

Yes, it should be safe to allow all but collections with overlapping polygons.  Not guaranteed that semantics won't change at some point in the future, though.

> So _if_ GEOS generally raises errors (instead of crashing) for cases it doesn't support (but does it do this generally?), this might already be good enough without specific checks needed in Shapely?

I'm pretty sure that inputs with overlapping polygons will always raise error, rather than crashing.  The downside to just reporting that error back to the user is that it is pretty low-level, and doesn't inform him of the real problem (overlapping polygon inputs).  Also, in the past the same error could be caused by a robustness issue, which made it even harder for the user to determine what was wrong.  However, that situation has (hopefully) been eliminated by OverlayNG, so  it *should* be safe to assume that an error indicates overlapping polygon input.

**Comment by jorisvandenbossche** [comment] 2021-09-15 09:38
@dr-jts thanks a lot for that detailed answer!

> I'm pretty sure that inputs with overlapping polygons will always raise error, rather than crashing. The downside to just reporting that error back to the user is that it is pretty low-level, and doesn't inform him of the real problem (overlapping polygon inputs). 

In that case, I think I would personally prefer to just pass inputs to GEOS. It is certainly true that the error from GEOS like "side location conflict at 1 2" is not at all informative (side question: is this something that could be improved in GEOS? Or is it too much down into the operation to have useful context to report about the error?). 
But checking in advance if polygons in collections are overlapping also doesn't sound that an attractive option. Alteratively, we could still catch the error from GEOS and reraise it with some additional explanation about what might be causing the issue.

**Comment by sgillies** [comment] 2021-10-03 22:39
@jorisvandenbossche since GEOS won't crash any more, let's close this one and address rough edges after 1.8.0. Okay?

**Comment by jorisvandenbossche** [comment] 2021-10-04 19:08
Yes, sounds good. Closing then.

**Closed by jorisvandenbossche** 2021-10-04 19:08 UTC
Labels: geos, bug
