### ISSUE TITLE
MacOSX 10.16 Big Sur: Error when importing geos: libc does not exists

### ISSUE THREAD

**Issue by ambientlight** [Toblerity/Shapely#946] opened 2020-07-16 17:37 UTC
Shapely 1.7.0 installation on **Big Sur** with geos installed via brew fails as in #888, curious if the fix simply does not apply to big sur yet.

Callstack:
```
File "/Users/hurden/.local/share/virtualenvs/sd-d1gC0yVG/lib/python3.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/Users/hurden/.local/share/virtualenvs/sd-d1gC0yVG/lib/python3.7/site-packages/shapely/geometry/base.py", line 18, in <module>
    from shapely.coords import CoordinateSequence
  File "/Users/hurden/.local/share/virtualenvs/sd-d1gC0yVG/lib/python3.7/site-packages/shapely/coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "/Users/hurden/.local/share/virtualenvs/sd-d1gC0yVG/lib/python3.7/site-packages/shapely/geos.py", line 138, in <module>
    free = load_dll('c').free
  File "/Users/hurden/.local/share/virtualenvs/sd-d1gC0yVG/lib/python3.7/site-packages/shapely/geos.py", line 62, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib c or load any of its variants [].
```

geos installation:
```
(sd) bash-3.2$ brew list geos
/usr/local/Cellar/geos/3.8.1_1/bin/geos-config
/usr/local/Cellar/geos/3.8.1_1/include/geos/ (409 files)
/usr/local/Cellar/geos/3.8.1_1/include/ (2 files)
/usr/local/Cellar/geos/3.8.1_1/lib/libgeos-3.8.1.dylib
/usr/local/Cellar/geos/3.8.1_1/lib/libgeos_c.1.dylib
/usr/local/Cellar/geos/3.8.1_1/lib/python3.8/ (4 files)
/usr/local/Cellar/geos/3.8.1_1/lib/ (4 other files)
```

**Comment by sgillies** [comment] 2020-07-16 22:18
Duplicate of #888

**Closed by sgillies** 2020-07-16 22:18 UTC
