### ISSUE TITLE
shapely.ops.split documentation discrepancy

### ISSUE THREAD

**Issue by redhog** [Toblerity/Shapely#641] opened 2018-09-24 07:50 UTC
## Expected behavior and actual behavior.

Documentation of shapely.ops.split says:

        Splits a geometry by another geometry and returns a collection of geometries. ... If the splitter does not split the geometry, a collection with a single geometry equal to the input geometry is returned.

However, an empty GeometryCollection is actually returned in this case. This is also documented in https://github.com/Toblerity/Shapely/issues/77 where it is discussed whether it should have returned None instead. However, both of those behaviors are invalid according to the documentation. 

## Steps to reproduce the problem.

    len(shapely.ops.split(polygon, line_that_does_not_intersect_the_polygon).geoms) == 0

## Operating system

Supposedly any, reproduced on ubuntu 18

## Shapely version and provenance

1.6.4.post2 installed using pip

**Comment by hoangphucITJP** [comment] 2019-06-07 13:28
I encounter this problem too

**Comment by drnextgis** [comment] 2019-06-18 18:01
Cannot reproduce it here:
```
>>> from shapely.geometry import Polygon, LineString
>>> from shapely.ops import split
>>> polygon = Polygon([(0, 0), (1, 1), (2, 0)])
>>> line = LineString([(10, 10), (20, 20)])
>>> result = split(polygon, line)
>>> len(result.geoms)
1
>>> result.wkt
'GEOMETRYCOLLECTION (POLYGON ((0 0, 1 1, 2 0, 0 0)))'
```

**Comment by drnextgis** [comment] 2019-06-18 20:32
@redhog @hoangphucITJP can you provide a reproducible test case?

**Comment by redhog** [comment] 2019-06-21 12:12
I don't any longer have the particular polygon I had problems with (I hacked my way around the problem and went on with the project, should have attached an example polygon, sorry), and yes, your minimal case works for me, so I assume this is a problem with more complicated polygons. Maybe polygons with certain properties, like the points being ordered in the wrong direction or something?  @hoangphucITJP , do you have an example polygon that behaves like this?

**Comment by drnextgis** [comment] 2019-06-21 15:08
@redhog thanks for your thoughts. @sgillies I think we can close this ticket unless someone provide a reproducible example of that issue. Also the title of ticket is not correct, it doesn't seem like a documentation issue.

**Closed** 2019-06-22 01:16 UTC
Labels: bug

**Comment by ikrets** [comment] 2022-01-04 13:14
@drnextgis I have also encountered this bug on shapely 1.8.0:

```python
from shapely.ops import split
from shapely import wkt

polygon = wkt.loads('POLYGON ((3.587905513704299 0.005285369279950692, 3.587905513704299 0.003523597748117689, 3.586315077550732 0.001763142929657249, 3.57672184747904 0.001771122349401158, 3.575114565862002 0, 3.568661517881182 0, 3.567042290959836 -0.001779008369381166, 3.565420684455624 -0.001780313225360942, 3.563796701666377 -0.00356321929312319, 3.560541620723346 -0.003568410656630397, 3.554003095187181 -0.01073580628850614, 3.554003095187181 -0.02146913838215357, 3.552362575793519 -0.02327426825201252, 3.55400309518718 -0.02504593871398638, 3.55400309518718 -0.04827544718571963, 3.555641263067542 -0.05002460873139877, 3.555641263067542 -0.05537396683348558, 3.554003095187181 -0.05719737719721798, 3.554003095187181 -0.06432843198090048, 3.552362575793519 -0.0661574229817978, 3.552362575793519 -0.06972221725573979, 3.550719708668961 -0.07155484846214337, 3.550719708668961 -0.07333739012611475, 3.549074497657434 -0.07517274885179824, 3.549074497657435 -0.07695559970110759, 3.547426946664597 -0.07879361716067797, 3.547426946664597 -0.08057672552345255, 3.542470293784956 -0.08610397256095016, 3.540813423165046 -0.08616402086084833, 3.529150626378395 -0.09912892321900112, 3.527475322987867 -0.09919613202092119, 3.525797736095032 -0.1010557850961197, 3.525797736095032 -0.1028477643364514, 3.522435731026134 -0.1065726988592409, 3.522435731026134 -0.1083650240596077, 3.51906465026467 -0.1120967755731862, 3.517375718999042 -0.1121710530421973, 3.515684533940032 -0.1140399824580383, 3.512295423222862 -0.1141897473819169, 3.510597508118757 -0.1160618877815056, 3.505490388527166 -0.1162875522805966, 3.503783575594005 -0.1181637092492077, 3.510597508118757 -0.1178587347953447, 3.512295423222862 -0.1195768265581217, 3.522435731026134 -0.1191039155864158, 3.527475322987867 -0.1242130570707078, 3.527475322987867 -0.1259943885927042, 3.534162788601622 -0.1327512378057773, 3.534162788601622 -0.1345237498886527, 3.537492727645056 -0.1378774970174063, 3.53915423302502 -0.1377827667483087, 3.540813423165046 -0.1394529963873645, 3.544124840667476 -0.1392599363122306, 3.547426946664597 -0.1425841562965806, 3.547426946664597 -0.1443419543642833, 3.587905513704299 -0.1417492248960894, 3.623813977817647 -0.1392555533862318, 3.623813977817647 -0.1375580868415166, 3.626875217149014 -0.1339477371552668, 3.626875217149014 -0.1322505393885675, 3.629926604646199 -0.1286481994134631, 3.629926604646199 -0.1269513827808265, 3.640528753885939 -0.1144048318328765, 3.640528753885939 -0.1093238875590875, 3.642033466737087 -0.1075412739536036, 3.642033466737087 -0.09906435803233024, 3.643535707233214 -0.09728762397538152, 3.645035474699129 -0.09720794013541227, 3.645035474699129 -0.08023472402345383, 3.643535707233214 -0.08030062711699992, 3.642033466737087 -0.07866365457031886, 3.642033466737087 -0.07696039400632573, 3.640528753885939 -0.07531829512238514, 3.640528753885939 -0.0719068043363934, 3.639021569401965 -0.07025781150259058, 3.639021569401965 -0.06854963621082694, 3.629926604646199 -0.05857731235306117, 3.628402142962103 -0.05862457587046687, 3.625345828364923 -0.05527211692078753, 3.623813977817647 -0.05531644563321801, 3.622279666765109 -0.0536340622599211, 3.620742896515615 -0.05367689897855418, 3.61920366842813 -0.05198995716636193, 3.617661983912554 -0.0520313056531195, 3.616117844429998 -0.0503398241478828, 3.614571251493059 -0.05037968845515704, 3.606801541571816 -0.04186901136265257, 3.606801541571816 -0.03315353058060504, 3.608360377270659 -0.03138518823038604, 3.608360377270659 -0.008720750420728347, 3.605240262590599 -0.005240736342242318, 3.605240262590599 -0.003493841998410212, 3.603676542207603 -0.0017482900433682, 3.602110382357064 -0.001749651598862712, 3.600541785027128 0, 3.595821388856556 0, 3.594243062577864 0.001756426132209415, 3.58949353274073 0.001760463343569791, 3.587905513704299 0.003523597748117689, 3.587905513704299 0.005285369279950692))')
line = wkt.loads("LINESTRING (0 -1.570796326794897, 0 1.570796326794897)")
print(split(polygon, line).wkt)
```

Prints `GEOMETRYCOLLECTION EMPTY`.

**Comment by drnextgis** [comment] 2022-01-04 18:37
@ikrets that is because of the invalid polygon:

```python
>>> from shapely.validation import explain_validity
>>> explain_validity(polygon)
'Self-intersection[3.5879055137043 0.00352359774811769]'
>>> explain_validity(polygon.buffer(0))
'Valid Geometry'
>>> print(split(polygon.buffer(0), line).wkt)
GEOMETRYCOLLECTION (POLYGON ((3.587905513704299 0.003523597748117689, 3.58949353274073 0.001760463343569791, 3.594243062577864 0.001756426132209415, 3.595821388856556 0, 3.600541785027128 0, 3.602110382357064 -0.001749651598862712, 3.603676542207603 -0.0017482900433682, 3.605240262590599 -0.003493841998410212, 3.605240262590599 -0.005240736342242318, 3.608360377270659 -0.008720750420728347, 3.608360377270659 -0.03138518823038604, 3.606801541571816 -0.03315353058060504, 3.606801541571816 -0.04186901136265257, 3.614571251493059 -0.05037968845515704, 3.616117844429998 -0.0503398241478828, 3.617661983912554 -0.0520313056531195, 3.61920366842813 -0.05198995716636193, 3.620742896515615 -0.05367689897855418, 3.622279666765109 -0.0536340622599211, 3.623813977817647 -0.05531644563321801, 3.625345828364923 -0.05527211692078753, 3.628402142962103 -0.05862457587046687, 3.629926604646199 -0.05857731235306117, 3.639021569401965 -0.06854963621082694, 3.639021569401965 -0.07025781150259058, 3.640528753885939 -0.0719068043363934, 3.640528753885939 -0.07531829512238514, 3.642033466737087 -0.07696039400632573, 3.642033466737087 -0.07866365457031886, 3.643535707233214 -0.08030062711699992, 3.645035474699129 -0.08023472402345383, 3.645035474699129 -0.09720794013541227, 3.643535707233214 -0.09728762397538152, 3.642033466737087 -0.09906435803233024, 3.642033466737087 -0.1075412739536036, 3.640528753885939 -0.1093238875590875, 3.640528753885939 -0.1144048318328765, 3.629926604646199 -0.1269513827808265, 3.629926604646199 -0.1286481994134631, 3.626875217149014 -0.1322505393885675, 3.626875217149014 -0.1339477371552668, 3.623813977817647 -0.1375580868415166, 3.623813977817647 -0.1392555533862318, 3.587905513704299 -0.1417492248960894, 3.547426946664597 -0.1443419543642833, 3.547426946664597 -0.1425841562965806, 3.544124840667476 -0.1392599363122306, 3.540813423165046 -0.1394529963873645, 3.53915423302502 -0.1377827667483087, 3.537492727645056 -0.1378774970174063, 3.534162788601622 -0.1345237498886527, 3.534162788601622 -0.1327512378057773, 3.527475322987867 -0.1259943885927042, 3.527475322987867 -0.1242130570707078, 3.522435731026134 -0.1191039155864158, 3.512295423222862 -0.1195768265581217, 3.510597508118757 -0.1178587347953447, 3.503783575594005 -0.1181637092492077, 3.505490388527166 -0.1162875522805966, 3.510597508118757 -0.1160618877815056, 3.512295423222862 -0.1141897473819169, 3.515684533940032 -0.1140399824580383, 3.517375718999042 -0.1121710530421973, 3.51906465026467 -0.1120967755731862, 3.522435731026134 -0.1083650240596077, 3.522435731026134 -0.1065726988592409, 3.525797736095032 -0.1028477643364514, 3.525797736095032 -0.1010557850961197, 3.527475322987867 -0.09919613202092119, 3.529150626378395 -0.09912892321900112, 3.540813423165046 -0.08616402086084833, 3.542470293784956 -0.08610397256095016, 3.547426946664597 -0.08057672552345255, 3.547426946664597 -0.07879361716067797, 3.549074497657435 -0.07695559970110759, 3.549074497657434 -0.07517274885179824, 3.550719708668961 -0.07333739012611475, 3.550719708668961 -0.07155484846214337, 3.552362575793519 -0.06972221725573979, 3.552362575793519 -0.0661574229817978, 3.554003095187181 -0.06432843198090048, 3.554003095187181 -0.05719737719721798, 3.555641263067542 -0.05537396683348558, 3.555641263067542 -0.05002460873139877, 3.55400309518718 -0.04827544718571963, 3.55400309518718 -0.02504593871398638, 3.552362575793519 -0.02327426825201252, 3.554003095187181 -0.02146913838215357, 3.554003095187181 -0.01073580628850614, 3.560541620723346 -0.003568410656630397, 3.563796701666377 -0.00356321929312319, 3.565420684455624 -0.001780313225360942, 3.567042290959836 -0.001779008369381166, 3.568661517881182 0, 3.575114565862002 0, 3.57672184747904 0.001771122349401158, 3.586315077550732 0.001763142929657249, 3.587905513704299 0.003523597748117689)))
```
