### ISSUE TITLE
geos_c.dll missing when shapely is installed in conda env using pip

### ISSUE THREAD

**Issue by ma0ho** [Toblerity/Shapely#1032] opened 2020-11-18 09:51 UTC
## Expected behavior and actual behavior.

When shapely is installed in a conda virtual environment, it cannot find `geos_c.dll`. Hence, it fails to import.

## Steps to reproduce the problem.

```bash
conda create -n shapelytest python=3.8
conda activate shapelytest
pip install shapely
python -c "from shapely.geometry import Point"
```

results in

```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Mathis\Anaconda3\envs\shapelytest\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "C:\Users\Mathis\Anaconda3\envs\shapelytest\lib\site-packages\shapely\geometry\base.py", line 19, in <module>
    from shapely.coords import CoordinateSequence
  File "C:\Users\Mathis\Anaconda3\envs\shapelytest\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "C:\Users\Mathis\Anaconda3\envs\shapelytest\lib\site-packages\shapely\geos.py", line 154, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "C:\Users\Mathis\Anaconda3\envs\shapelytest\lib\ctypes\__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\Mathis\Anaconda3\envs\shapelytest\Library\bin\geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

This is only fixed by installing it again using conda:

```bash
conda install shapely
```

## Operating system

Windows 10

## Shapely version and provenance

1.7.1 (pypi)

**Comment by ocefpaf** [comment] 2020-11-18 12:07
@ma0ho this is not an issue with shapely. While one can mix conda and pip packages, that is not recommended unless you really know what you are doing. Wheels, what you get when you do a pip install, bundles the dependencies, in that case geos. Conda will bring you its own dependencies and set the paths. That is probably why the wheels is not working. Shapely is looking for a geos that does not exist in the conda path.

**Comment by jorisvandenbossche** [comment] 2020-11-18 13:02
See also https://github.com/Toblerity/Shapely/pull/843, this is specifically an issue on windows (for other platforms Shapely checks if the file actually exists). 

(although I wouldn't recommend this myself, I will continue to argue that we should either support it or either raise an informative error, because however you want it to be, people will always be doing `pip install shapely` in conda envs ..)

**Comment by ma0ho** [comment] 2020-11-18 14:36
In general, I agree to your arguments. In particular, I'd support the argument that probably many people use pip packages in conda. I personally do this as well, because conda is very handy to set up virtual environments.. However, pip often supports more packages and I often find myself using only pip packages in conda (which is then also not a mix anymore). Therefore, it would be great if shapely would have support for that.. Maybe you could simply check both paths?

**Comment by ocefpaf** [comment] 2020-11-18 16:58
The problem is is that by opening issues that are conda related upstream we get a lot of bad comments from library authors b/c they don't want this extra problem on their lap. We even get a few upstream authors to request that we remove the package from conda-forge.

PS: why not pyvenv? I'm a big fan of conda environment management but using all pip installs on a clean conda env seems an extra unnecessary complexity.

**Comment by sgillies** [comment] 2020-11-18 17:50
Closing this one as it's a known issue.

**Closed by sgillies** 2020-11-18 17:50 UTC

**Comment by longhan-airborne** [comment] 2021-03-23 06:02
download geos_c.dll online, then put it into your lib address. it works for me

**Comment by jorisvandenbossche** [comment] 2021-03-23 12:42
Note that this will be fixed in Shapely 1.8 (upcoming release), see https://github.com/Toblerity/Shapely/pull/1108

**Comment by A-A-Augustin** [comment] 2021-05-30 08:50
> download geos_c.dll online, then put it into your lib address. it works for me

Had the same issue with keras_ocr, and this worked for me aswell, thanks !

**Comment by freshskates** [comment] 2021-09-10 05:33
is there a fix to this issue?

**Comment by freshskates** [comment] 2021-09-10 05:45
I was having this issue with installing arcade and I fixed it with 
conda install shapely
pip install arcade
