### ISSUE TITLE
fiona + shapely.speedups breaks LineString.interpolate()

### ISSUE THREAD

**Issue by lx-88** [Toblerity/Shapely#353] opened 2016-01-11 00:07 UTC
I'm not sure if I should report this here or at Fiona but here goes. If I import fiona before shapely, LineString.interpolate() prints **"IllegalArgumentException: LinearIterator only supports lineal geometry components"** which is followed by a **"ValueError: No Shapely geometry can be created from null value"** error.

The error does not trigger if any of the following are true:
* I dont import fiona
* I import fiona AFTER shapely
* I don't enable shapely.speedups

My environment is the following:
* Shapely 1.5.13
* Fiona 1.6.3
* GEOS 3.5.0
* Mac OS X 10.9.5
* Python 2.7.10 (default, Jul 13 2015, 12:18:59)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
* python installed through Homebrew

### The following fails
```python
"""
This fails with the following:

IllegalArgumentException: LinearIterator only supports lineal geometry components
Traceback (most recent call last):
  File "linear_referencing_bug.py", line 11, in <module>
    print test_shape.interpolate(1, normalized=False)
  File "/usr/local/lib/python2.7/site-packages/shapely/impl.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/shapely/geometry/base.py", line 709, in interpolate
    return geom_factory(op(self, distance))
  File "/usr/local/lib/python2.7/site-packages/shapely/geometry/base.py", line 65, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value


Shapely 1.5.13
Fiona 1.6.3
GEOS 3.5.0
Mac OS X 10.9.5
Python 2.7.10 (default, Jul 13 2015, 12:18:59)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Installed through Homebrew
"""
import fiona
import shapely.speedups
if shapely.speedups.available:
    shapely.speedups.enable()
import shapely
from shapely.geometry import shape, LineString

test_geom = {'type': 'LineString', 'coordinates': [(639201.0379574801, 1612088.5377595278), (639201.0379574801, 1611977.218462066), (639179.8342817731, 1611881.8019213844), (639179.8342817731, 1611791.6862996297), (639179.8342817731, 1611685.6679210947), (639201.0379574801, 1611595.5522993398)]}
test_shape = shape(test_geom)

print test_shape.interpolate(1, normalized=False)
```

### This works as expected
It also works if I completely omit the fiona import.
```python
import shapely.speedups
if shapely.speedups.available:
    shapely.speedups.enable()
import shapely
from shapely.geometry import shape, LineString
import fiona

test_geom = {'type': 'LineString', 'coordinates': [(639201.0379574801, 1612088.5377595278), (639201.0379574801, 1611977.218462066), (639179.8342817731, 1611881.8019213844), (639179.8342817731, 1611791.6862996297), (639179.8342817731, 1611685.6679210947), (639201.0379574801, 1611595.5522993398)]}
test_shape = shape(test_geom)

print test_shape.interpolate(1, normalized=False)
```

**Comment by sgillies** [comment] 2016-01-24 00:01
Thanks for the report, @lx-88, and apologies for the slow response. We've got a problem between Fiona and Shapely with double `dlopen()` calls on GEOS: #324.

I've solved this for the OS X wheels I'm uploading to PyPI, but it looks like the fix isn't helping you. Would you be willing to scan #324 and https://github.com/Toblerity/Shapely/pull/327#issuecomment-146634606 and let me know if the Fiona and Shapely wheels I have on PyPI work for you?

**Comment by lx-88** [comment] 2016-01-25 01:18
@sgillies, I still see the same behavior even after nuking my pip cache and a fresh virtualenv and the behavior is the same working with system python (i.e., no virtualenv). Maybe I'm missing where to find the specific wheels you're talking about or there is something odd about my system. If so, I have no idea what that might be.

**test.py**
```python
import fiona
import shapely.speedups
if shapely.speedups.available:
    shapely.speedups.enable()
import shapely
from shapely.geometry import shape, LineString

test_geom = {'type': 'LineString', 'coordinates': [(639201.0379574801, 1612088.5377595278), (639201.0379574801, 1611977.218462066), (639179.8342817731, 1611881.8019213844), (639179.8342817731, 1611791.6862996297), (639179.8342817731, 1611685.6679210947), (639201.0379574801, 1611595.5522993398)]}
test_shape = shape(test_geom)

print test_shape.interpolate(1, normalized=False)
```

**Running test.py**
```bash
(venv)$ pip install --ignore-installed Shapely
Collecting Shapely
  Using cached Shapely-1.5.13-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: Shapely
Successfully installed Shapely-1.5.13
(venv)$ pip install --ignore-installed Shapely
Collecting Shapely
  Downloading Shapely-1.5.13-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 224kB/s 
Installing collected packages: Shapely
Successfully installed Shapely-1.5.13
(venv)$ pip install --ignore-installed Fiona
Collecting Fiona
  Downloading Fiona-1.6.3-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (15.1MB)
    100% |████████████████████████████████| 15.1MB 31kB/s 
Collecting six (from Fiona)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting cligj (from Fiona)
  Downloading cligj-0.4.0-py2-none-any.whl
Collecting click-plugins (from Fiona)
  Downloading click-plugins-1.0.3.tar.gz
Collecting click>=4.0 (from cligj->Fiona)
  Downloading click-6.2-py2.py3-none-any.whl (70kB)
    100% |████████████████████████████████| 73kB 3.7MB/s 
Building wheels for collected packages: click-plugins
  Running setup.py bdist_wheel for click-plugins ... done
  Stored in directory: <full user path>/Library/Caches/pip/wheels/fb/1b/1a/7d05eb78394e4b4994c34d39c23df392af15b5c1e34ae2c74a
Successfully built click-plugins
Installing collected packages: six, click, cligj, click-plugins, Fiona
Successfully installed Fiona-1.6.3 click-6.2 click-plugins-1.0.3 cligj-0.4.0 six-1.10.0
(venv)$ python test.py
IllegalArgumentException: LinearIterator only supports lineal geometry components
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    print test_shape.interpolate(1, normalized=False)
  File "venv/lib/python2.7/site-packages/shapely/impl.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "venv/lib/python2.7/site-packages/shapely/geometry/base.py", line 709, in interpolate
    return geom_factory(op(self, distance))
  File "venv/lib/python2.7/site-packages/shapely/geometry/base.py", line 65, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value
```

**Comment by snorfalorpagus** [comment] 2016-02-17 12:06
I can reproduce this with the wheels on PyPI. On OS X I created a new conda environment, then used pip to install shapely and fiona, and get the exception above.

**Comment by snorfalorpagus** [comment] 2016-03-25 23:39
I've tried to investigate this a little more. Here's what I've found.

It seems the problems start in the example above at the first call into the cython code. In this case, the creation of a LineString calls `geos_linestring_from_py`. The problem isn't related to `interpolate`, but actually occurs in `shape`. This can be seen if you try and print the geometry - the WKT is an empty string.

So, using the following code, with Fiona (installed using the wheel on pypi):

```
import fiona
import shapely.speedups
if shapely.speedups.available:
    shapely.speedups.enable()
import shapely
from shapely.geometry import shape, LineString
print(shapely.geos._lgeos.GEOSversion())
test_geom = {'type': 'LineString', 'coordinates': [(639201.0379574801, 1612088.5377595278), (639201.0379574801, 1611977.218462066), (639179.8342817731, 1611881.8019213844), (639179.8342817731, 1611791.6862996297), (639179.8342817731, 1611685.6679210947), (639201.0379574801, 1611595.5522993398)]}
print(shapely.__version__)
a = LineString(test_geom['coordinates'])
print(a.coords[:])
```

With Shapely 1.5.13 from the pypi wheel:

```
b'3.4.2-CAPI-1.8.2 r3921'
1.5.13
Geometry must be a Point or LineString
Geometry must be a Point or LineString
Segmentation fault: 11
```

With Shapely 1.5.13 built locally from maint-1.5:

```
b'3.4.2-CAPI-1.8.2 r3921'
1.5.13
Assertion failed: (0 != cs), function GEOSCoordSeq_setOrdinate_r, file geos_ts_c.cpp, line 3657.
Abort trap: 6
```

With Shapely 1.6 build locally from master:

```
b'3.4.2-CAPI-1.8.2 r3921'
1.6dev0
[(639201.0379574801, 1612088.5377595278), (639201.0379574801, 1611977.218462066), (639179.8342817731, 1611881.8019213844), (639179.8342817731, 1611791.6862996297), (639179.8342817731, 1611685.6679210947), (639201.0379574801, 1611595.5522993398)]
```

So has this been fixed in master? If so, what changed and can we backport to 1.5.x? Interestingly, maint-1.4 seems to be OK too.

Unfortunately I'm not able to test this full as I can't seem to build a wheel myself. The wheel builds, but I'm unable to relocate it as the extensions have @rpaths in them already:

```
(python34)snorfmac:Shapely snorf$ otool -L build/lib.macosx-10.5-x86_64-3.4/shapely/speedups/_speedups.so 
build/lib.macosx-10.5-x86_64-3.4/shapely/speedups/_speedups.so:
	@rpath/./libgeos_c.1.dylib (compatibility version 10.0.0, current version 10.2.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

Ideally I'd like to work out why this is the case and fix it, but in the mean time, @sgillies could you build a wheel based on the master branch and see if this is still an issue?

**Comment by sgillies** [comment] 2016-03-27 21:23
@snorfalorpagus here's a difference between maint-1.5 and master: https://github.com/Toblerity/Shapely/blob/maint-1.5/shapely/geos.py#L72-L80. In 1.5 I'm trying to reuse a loaded DLL, but it appears to be breaking something in your case.

**Comment by sgillies** [comment] 2016-03-28 02:48
@snorfalorpagus Thanks for the test script. I can confirm that #374 (in conjunction with static GEOS in Rasterio/Fiona OS X wheels) fixes this.

**Closed by sgillies** 2016-03-28 02:48 UTC
Labels: bug, geos

**Comment by sgillies** [comment] 2018-01-01 22:12
See also #553.
