### ISSUE TITLE
Casting Polygon as MultiPolygon

### ISSUE THREAD

**Issue by poplarShift** [Toblerity/Shapely#648] opened 2018-10-17 19:47 UTC
The output of some operations, such as unions, depends on the outcome, such as Polygon vs. MultiPolygon as result of a union. This may pose a problem when one of the two types is assumed:

```
from shapely.geometry import Point, MultiPolygon

c = Point(0,0).buffer(1)
c2 = Point(2,0).buffer(1)

print(type(c))
print(type(MultiPolygon([c])))
print(type(c.union(c2)))
print(type(c.union(c)))
```
> <class 'shapely.geometry.polygon.Polygon'>
> <class 'shapely.geometry.multipolygon.MultiPolygon'>
> <class 'shapely.geometry.multipolygon.MultiPolygon'>
> <class 'shapely.geometry.polygon.Polygon'>

So when I want to subclass MultiPolygon:
```
class myclass(MultiPolygon):
    pass
myclass(c.union(c2))
myclass(c.union(c))
```
it throws an error
> TypeError: 'Polygon' object is not iterable

because `geos_multipolygon_from_polygons` (https://github.com/Toblerity/Shapely/blob/master/shapely/geometry/multipolygon.py#L62) doesn't seem to know what to do with it.

Is there a reason that MultiPolygon should not allow direct casting from a Polygon, i.e. `MultiPolygon(Polygon())`?

PS I'm on 1.6.4 (conda-forge).

**Comment by sgillies** [comment] 2018-10-27 05:33
@poplarShift I get what you're asking about. The MultiPolygon constructor requires a sequence of polygons because that is an unambiguous case and we follow the 12th point of https://www.python.org/dev/peps/pep-0020/. I suppose we could allow MultiPolygon() to take a single polygon. We could also take a linear ring, right? and close it into a polygon. We could also take any given linestring and close it into a ring. I'm not making a slippery slope argument here, but trying to point out that Shapely doesn't want to be too smart, instead we want developers to be very specific about their intents, even at the expense of a few extra lines of code to marshal single polygons into sequences.

The solution to the problem is not to assume a type for the output. That's the best Shapely can offer.

**Closed by sgillies** 2018-10-27 05:33 UTC

**Comment by poplarShift** [comment] 2018-11-04 13:06
Thanks! So basically, if the intent is "unary union" and it's impossible to know what the outcome will be, that means a few conditionals after each unary union to determine which of the two it is to do further stuff with it (in the cases where it matters), but OK.
