### ISSUE TITLE
Why a size shift after rotation

### ISSUE THREAD

**Issue by TimFruition** [Toblerity/Shapely#620] opened 2018-07-31 09:20 UTC
Hi! 
I'm working on a python process where I create a square grid and I rotate it.
All spatial operations are done with Geopandas, so geometric operations with Shapely.

Before I rotate the grid, all squares have the good size (10m for ex), but after rotation operation, they are smaller (7m approximately).

I tried all possible options in the rotate process, but no good result.

Is there a reason that this is happening ?

I installed Geopandas and Shapely with Pip, and Shapely version is 1.6.4.post2.
I'm under MacOS High Sierra.

Here is a part of the code I wrote:

    Xmin, Ymin, Xmax, Ymax = buffer_CH.total_bounds # coordonées de la bounding box du buffer de l'enveloppe concave

    cols = abs(int((Xmax - Xmin) / W))+1 # nombre de colonnes
    rows = abs(int((Ymin - Ymax) / H))+1 # nombre de lignes

    XleftOri, XrightOri, Ybottom, Ytop = Xmin, Xmin+W, Ymin, Ymin+H
    polygons = []

    for r in range(rows):
        Xleft = XleftOri
        Xright = XrightOri
        for c in range(cols):
            polygon = Polygon([(Xleft,Ybottom),(Xright,Ybottom),(Xright,Ytop),(Xleft,Ytop)])
            polygons.append(polygon)
            Xleft = Xright
            Xright += W
        Ybottom = Ytop
        Ytop += H

    grid = gpd.GeoDataFrame({'geometry':polygons})
    grid.crs = {'init': 'epsg:3857'}
    grid.to_file("{0}/{1}_{2}_zonage-carre/{3}-Grid.shp".format(os.chdir, date, folder_name, shp_name))

        # Rotation inverse de la grille
    rotate_grid = grid.rotate(angleinverse, origin=(0,0), use_radians=True) # Rotation
    rotate_grid = gpd.GeoDataFrame(rotate_grid) # Conversion de la GeoSerie en GeoDataFrame
    rotate_grid.crs = {'init': 'epsg:3857'}
    rotate_grid = rotate_grid.rename(columns={0:'geometry'}).set_geometry('geometry') # Identification de la colonne geometry
    rotate_grid.crs = {'init': 'epsg:3857'} # attribution du crs
    rotate_grid.to_file("{0}/{1}_{2}_zonage-carre/{3}-RotateGrid.shp".format(os.chdir, date, folder_name, shp_name))

**Comment by sgillies** [comment] 2018-07-31 14:51
Can you please provide an example that uses only shapely code and a single geometry? Otherwise, I think you should take this issue to the GeoPandas issue tracker.

**Comment by kannes** [comment] 2018-08-05 09:34
It looks like you rotate all your polygons around the origin of EPSG:3857 while your data is local to somewhere else. This will shift your polygons to different places on (a projection of) earth.

**Comment by sgillies** [comment] 2018-08-06 21:51
I can't reproduce it using only Shapely and so I will close this issue.

![untitled](https://user-images.githubusercontent.com/33697/43742762-6dfbefb0-9990-11e8-8379-8cf424c9c055.png)

Please do reopen it if you find some Shapely code that demonstrates the problem.

**Closed by sgillies** 2018-08-06 21:51 UTC
