### ISSUE TITLE
PyPy3.5 crash when printing Shapely objects

### ISSUE THREAD

**Issue by wwoods** [Toblerity/Shapely#601] opened 2018-06-23 20:02 UTC
## Expected behavior and actual behavior.

This script should run without crashing 100% of the time (MWE; I tried just creating and printing `shapely.geometry.point.Point` objects, but something about the way they are instantiated through geopandas seems responsible):

    import geopandas as gpd
    gdf = gpd.read_file('./Parks_Tree_Inventory.geojson')
    s = gdf.loc[0]['geometry']
    for _ in range(10000):
        print(s)

Other geojson files cause the same issue (that particular one is from Portland Maps' Open Data website).  Printing anything other than the Shapely object does not crash.  It is the repeated printing of the geometry, which is a Shapely object, that causes the following crash:

    $ pypy3 pypy_crash.py
    ...
    POINT (-122.6936400358276 45.57490683451324)
    POINT (-122.6936400358276 45.57490683451324)
    RPython traceback:
      File "rpython_jit_metainterp.c", line 38458, in handle_jitexception_12
      File "rpython_jit_metainterp_2.c", line 8448, in execute_assembler__star_2_4
      File "rpython_jit_metainterp_7.c", line 39224, in AbstractResumeGuardDescr_handle_fail
      File "rpython_jit_metainterp_7.c", line 48400, in AbstractResumeGuardDescr__trace_and_compile_from
      File "rpython_jit_metainterp_7.c", line 55647, in MetaInterp_handle_guard_failure
      File "rpython_jit_metainterp_7.c", line 58699, in MetaInterp__handle_guard_failure
      File "rpython_jit_metainterp_1.c", line 4610, in MetaInterp__interpret
      File "rpython_jit_metainterp_2.c", line 21043, in MIFrame_run_one_step
      File "rpython_jit_metainterp_4.c", line 9899, in handler_ref_return_1
      File "rpython_jit_metainterp_4.c", line 59551, in MetaInterp_finishframe
    *** Invalid usage of a dying CPython object ***

    cpyext, the emulation layer, detected that while it is calling
    an object's tp_dealloc, the C code calls back a function that
    tries to recreate the PyPy version of the object.  Usually it
    means that tp_dealloc calls some general PyXxx() API.  It is
    a dangerous and potentially buggy thing to do: even in CPython
    the PyXxx() function could, in theory, cause a reference to the
    object to be taken and stored somewhere, for an amount of time
    exceeding tp_dealloc itself.  Afterwards, the object will be
    freed, making that reference point to garbage.
    >>> PyPy could contain some workaround to still work if
    you are lucky, but it is not done so far; better fix the bug in
    the CPython extension.
    Aborted

## Steps to reproduce the problem.

Run the script above.

## Operating system

Solus 3.9999

## Shapely version and provenance

Both 1.6.4.post1 and the `master` branch through pip.

**Comment by snorfalorpagus** [comment] 2018-08-06 21:43
I can reproduce this with both `wkt` and `wkb`:

```python
import geopandas as gpd
gdf = gpd.read_file('./stations.geojson')
geom = gdf.loc[0]['geometry']
from shapely.wkb import dumps
for n, _ in enumerate(range(10000)):
    dumps(geom)
```

**Comment by snorfalorpagus** [comment] 2018-08-06 22:31
I can't see any problems looking at the wkt/wkb code.

Interestingly, the segfault happens even if the geometry being used isn't from the dataframe:

```
import geopandas as gpd
from shapely.geometry import shape, mapping
from shapely.wkt import dumps
gdf = gpd.read_file('./stations.geojson')  # doesn't crash without this
x = {'type': 'Point', 'coordinates': (-77.12911152370515, 38.79930767201779)}
print(x)
y = shape(x)
for n, _ in enumerate(range(10000)):
    dumps(y)
```

**Comment by snorfalorpagus** [comment] 2018-08-06 22:37
Noticed that this is probably a duplicate of https://github.com/Toblerity/Fiona/issues/553

Based on this requiring the GeoPandas `read_file` call, I suspect it's more likely Fiona than Shapely.

**Closed by snorfalorpagus** 2018-08-06 22:37 UTC
Labels: bug
