### ISSUE TITLE
buffer trims multilinestring

### ISSUE THREAD

**Issue by Dinosaver** [Toblerity/Shapely#1004] opened 2020-10-14 10:27 UTC
##  Expected behavior and actual behavior.

When I try to buffer a multilinestring it trims it to a half

## Steps to reproduce the problem.

MLS = 'MULTILINESTRING ((1.312336712598466 0.6561695538052278, 0.656168733595841 0.3280855643039118), (0.656168733595841 0.3280855643039118, 7.545932163566249e-07 1.574802595882829e-06), (7.545932163566249e-07 1.574802595882829e-06, -0.6561672244094083 -0.3280824146987201), (-0.6561672244094083 -0.3280824146987201, -1.312335203412033 -0.656166404200036))'
MLS_buff = MLS.buffer(0.5/304.8)

the result:
MLS_buff = 'POLYGON ((0.0007343726960706248 -0.001465661403112638, 0.000587025827315611 -0.001530503408281476, 0.0004340328460877666 -0.001580590662760421, 0.0002768671584307847 -0.001615440798908363, 0.000117042355832306 -0.001634718190863176, -4.390236148952165e-05 -0.00163823718680224, -0.000204417007925557 -0.001625963896870982, -0.0003629557396843898 -0.001598016519560704, -0.0005179917421130958 -0.001554664203392495, -0.0006680319337569868 -0.00149632445486984, -0.00081163134555022 -0.001423559117662764, -0.0009474070366578038 -0.001337068961746149, -0.001074051412951829 -0.001237686934601803, -0.001190344819857725 -0.001126370139478866, -0.001295167288294546 -0.001004190617966324, -0.001387509320589455 -0.000872325025646462, -0.001466481612492163 -0.0007320433002583856, -0.001531323617661001 -0.0005846964315033744, -0.001581410872139946 -0.0004317034502755305, -0.001616261008287889 -0.0002745377626185482, -0.001635538400242702 -0.0001147129600200692, -0.001639057396181766 4.62317573017581e-05, -0.001626784106250509 0.0002067464037377931, -0.001598836728940231 0.0003652851354966256, -0.001555484412772022 0.0005203211379253313, -0.001497144664249368 0.0006703613295692222, -0.001424379327042292 0.0008139607413624555, -0.001337889171125679 0.0009497364324700389, -0.001238507143981333 0.001076380808764064, -0.001127190348858397 0.00119267421566996, -0.001005010827345855 0.001297496684106781, -0.0008731452350259939 0.001389838716401691, -0.0007328635096379184 0.0014688110083044, 0.6554351154929858 0.3295528005096199, 0.6554351154929867 0.3295528005096204, 1.311603094495611 0.6576367900109363, 1.311750441364367 0.6577016320161051, 1.311903434345594 0.6577517192705841, 1.312060600033251 0.6577865694067321, 1.31222042483585 0.6578058467986868, 1.312381369553172 0.6578093657946259, 1.312541884199608 0.6577970925046946, 1.312700422931367 0.6577691451273844, 1.312855458933795 0.6577257928112161, 1.313005499125439 0.6576674530626935, 1.313149098537232 0.6575946877254865, 1.31328487422834 0.6575081975695698, 1.313411518604634 0.6574088155424255, 1.31352781201154 0.6572974987473026, 1.313632634479977 0.65717531922579, 1.313724976512272 0.6570434536334702, 1.313803948804174 0.656903171908082, 1.313868790809343 0.6567558250393271, 1.313918878063822 0.6566028320580992, 1.31395372819997 0.6564456663704422, 1.313973005591925 0.6562858415678438, 1.313976524587864 0.6561248968505219, 1.313964251297933 0.6559643822040859, 1.313936303920622 0.6558058434723271, 1.313892951604454 0.6556508074698983, 1.313834611855931 0.6555007672782545, 1.313761846518724 0.6553571678664613, 1.313675356362808 0.6552213921753536, 1.313575974335663 0.6550947477990596, 1.31346465754054 0.6549784543921537, 1.313342478019028 0.6548736319237168, 1.313210612426708 0.654781289891422, 1.31307033070132 0.6547023175995192, 0.6569023516986963 0.3266183280982038, 0.6569023516986954 0.3266183280982033, 0.0007343726960706248 -0.001465661403112638))'

## Operating system

Win10x64

## Shapely version and provenance

Shapely 1.7

**Comment by mwtoews** [comment] 2020-10-14 21:33
I can't reproduce the unexpected polygon. How did you install shapely? What is the output from:
```python
import shapely
from shapely import geos
print(shapely.__version__)
print(geos.geos_version_string)
```

**Comment by Jeremiah-England** [comment] 2020-10-18 21:04
I can't reproduce it from the original either. But I can by dropping the last LineString in the MLS.

```python
from shapely.geometry import MultiLineString
from shapely import wkt

mls = wkt.loads('MULTILINESTRING ((1.312336712598466 0.6561695538052278, 0.656168733595841 0.3280855643039118), (0.656168733595841 0.3280855643039118, 7.545932163566249e-07 1.574802595882829e-06), (7.545932163566249e-07 1.574802595882829e-06, -0.6561672244094083 -0.3280824146987201), (-0.6561672244094083 -0.3280824146987201, -1.312335203412033 -0.656166404200036))')

print(MultiLineString(mls[:-2]).buffer(0.5 / 304.8).wkt)
```
@Dinosaver is it at all possible that somehow the last LineString is not making it into the MLS that you call `buffer` on? That would be a nice resolution! :)

**Comment by sgillies** [comment] 2020-11-09 03:05
Closing for lack of reply.

**Closed by sgillies** 2020-11-09 03:05 UTC
