### ISSUE TITLE
`convex_hull` error after `cascaded_union` of two polygons

### ISSUE THREAD

**Issue by siyangy** [Toblerity/Shapely#902] opened 2020-04-23 22:57 UTC
## Please note
I'm trying to union two polygons and call a convex_hull against the result. 
However, the cascaded_union returned a `MultiPolygon` instead of a `Polygon` (is that an indication that something is wrong?) and a later `convex_hull` call gave me **'No Shapely geometry can be created from null value'**. The `is_valid` call returns true for both the input polygons and the output multi polygon.

Here are the coordinates of the two input polygons and plot, which all seem normal:
```python
polygon_a = [
    (-611.7893942183597, 31.624461258744013), 
    (-606.3143806506498, 34.12236530751251), 
    (-605.9562600088188, 34.51626554959586), 
    (-605.9372782368359, 34.554556481477384), 
    (-605.9389870500697, 34.632406881530706), 
    (-606.1890650621804, 35.40721370695477), 
    (-606.2610231848747, 35.56493461631187), 
    (-606.6823007620468, 36.261633856900616), 
    (-606.7399783885497, 36.313949210594544), 
    (-606.7813391999337, 36.32470962014202), 
    (-607.3135575499375, 36.3124042254764), 
    (-612.7885711176474, 33.8145001767079), 
    (-612.6761855671084, 33.39528624498644), 
    (-612.0323516863292, 31.98410344380743), 
    (-611.7893942183597, 31.624461258744013)
]

polygon_b = [
    (-662.0863689755408, 8.677117780411429), 
    (-656.611355407831, 11.175021829179927), 
    (-656.253234766, 11.56892207126327), 
    (-656.2342529940171, 11.607213003144798), 
    (-656.2359618072509, 11.68506340319812), 
    (-656.4860398193615, 12.459870228622187), 
    (-656.5579979420559, 12.617591137979284), 
    (-656.9792755192279, 13.314290378568028), 
    (-657.0369531457309, 13.366605732261963), 
    (-657.0783139571148, 13.37736614180944),
    (-657.6105323071187, 13.365060747143819), 
    (-663.0855458748285, 10.867156698375318), 
    (-662.9731603242896, 10.447942766653856), 
    (-662.3293264435104, 9.036759965474847), 
    (-662.0863689755408, 8.677117780411429)
]
```

<img width="920" alt="Screen Shot 2020-04-23 at 3 23 47 PM" src="https://user-images.githubusercontent.com/15767981/80157438-06d02f80-857b-11ea-9a32-584f4bf0ddd0.png">

## Expected behavior and actual behavior.
Get a convex hull

## Operating system

Linux

## Shapely version and provenance

Version: 1.5.13

**Comment by snorfalorpagus** [comment] 2020-05-01 08:44
I can't reproduce this with Shapely 1.7.0 and GEOS 3.8.0.

```python
>>> union = cascaded_union([Polygon(polygon_a), Polygon(polygon_b)])
>>> print(type(union).__name__)
MultiPolygon
>>> hull = union.convex_hull
>>> print(hull.area)
148.99912052583682
```

The union returns a MultiPolygon because the two inputs do not intersect. This is expected.

@siyangy Shapely 1.5.13 is very old (released in 2015). Is it possible for you to upgrade? It's unlikely that any fix will be backported.

**Closed** 2020-05-31 00:54 UTC
Labels: wontfix
