### ISSUE TITLE
nearest_points Returns Incorrect Result

### ISSUE THREAD

**Issue by MikeTho16** [Toblerity/Shapely#560] opened 2018-01-26 01:27 UTC
If the first feature is a subset of the second, and if they do not share vertices, nearest_points() returns [POINT (0 0), POINT (0 0)] rather than one of the expected results. Switching the order that the features are passed to nearest_points() produces one of the expected results.

## Expected behavior and actual behavior.

Expected:
POINT (1 1.666666666666667)
POINT (1 1.666666666666667)

or

POINT (2 3.333333333333334)
POINT (2 3.333333333333334)

Actual:

POINT (0 0)
POINT (0 0)

## Steps to reproduce the problem.
        from shapely.geometry import LineString
        from shapely.ops import nearest_points
        for x in nearest_points(LineString([(1, 5.0/3.0), (2, 10.0/3.0)]), LineString([(3, 5), (0, 0)])):
            print x

## Operating system

Windows 10 Enterprise 10.0.15063 Build 15063

## Shapely version and provenance

1.5.17 from https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely

and

1.6.4.post1 from https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely

**Comment by sgillies** [comment] 2018-01-26 01:48
@MikeTho16 can you check and see if this is still a problem with shapely 1.6.4? We're not fixing any more bugs in the 1.5 branch.

**Comment by MikeTho16** [comment] 2018-01-26 03:23
@sgillies Sure, I will do so over the next few days.

**Comment by MikeTho16** [comment] 2018-01-26 22:08
@sgillies I upgraded to the 1.6.4.post1 (the latest version on the gohlke site) and got the same results.  I updated my original issue comment to reflect the fact that it happens in both versions that I have tried.

**Comment by snorfalorpagus** [comment] 2018-01-27 13:50
Interestingly the order of the geometries as passed to `nearest_points` is significant:

```
>>> [g.wkt for g in nearest_points(l1, l2)]
['POINT (0 0)', 'POINT (0 0)']
>>> [g.wkt for g in nearest_points(l2, l1)]
['POINT (1 1.666666666666667)', 'POINT (1 1.666666666666667)']
```

The `nearest_points` function is a very thin wrapper around the `GEOSNearestPoints` method. I can't see anything wrong with the code in Shapely, so suspect this is a problem with GEOS. Tested with GEOS 3.6.2 (from conda-forge).

https://github.com/Toblerity/Shapely/blob/272f35db782eaaf5e14e65cb434f487b19c96a97/shapely/ops.py#L259-L280

**Comment by elrapha** [comment] 2020-07-22 14:40
poly = Polygon([(41.80550797625462, 41.37394100717459), (41.7832582995143, 41.35589527080451),
                    (41.76102983031871, 41.33786173767593), (41.78550304726648, 41.32085593770037),
                    (41.80995293727565, 41.30386191464755), (41.83220261401596, 41.32192207197944),
                    (41.85443108321155, 41.33996001855137), (41.82995786626379, 41.35696083166484),
                    (41.80550797625462, 41.37394100717459)])

    y, x = nearest_points(poly.boundary, poly.centroid)
    xy = LineString((x, y))


When i plot the polygon and the xy line I get 

![Figure_1](https://user-images.githubusercontent.com/1866842/88189887-df503800-cc39-11ea-976b-46455042b525.png)

It does not look like the closest point to me. I  would expect that the closest point results in a  perpendicular line

**Comment by mwtoews** [comment] 2020-07-22 23:21
> It does not look like the closest point to me. I would expect that the closest point results in a perpendicular line

This does not appear to be related to the behavior described for this ticket. The above result looks fine to me, as it picked the closest point in Cartesian space.

**Comment by mwtoews** [comment] 2020-07-22 23:28
For the record, I can't reproduce the behavior in this ticket with Shapely 1.7 with 3.8.0-CAPI-1.13.1 on Windows. My suspicion is that this has been fixed with the upstream version of GEOS.

```pycon
>>> from shapely.geometry import Polygon, LineString
>>> from shapely.ops import nearest_points
>>> l1 = LineString([(1, 5.0/3.0), (2, 10.0/3.0)])
>>> l2 = LineString([(3, 5), (0, 0)])
>>> [g.wkt for g in nearest_points(l1, l2)]
['POINT (2 3.333333333333333)', 'POINT (2 3.333333333333333)']
>>> [g.wkt for g in nearest_points(l2, l1)]
['POINT (2 3.333333333333333)', 'POINT (2 3.333333333333333)']
>>> for x in nearest_points(l1, l2):
...     print(x)
...
POINT (2 3.333333333333333)
POINT (2 3.333333333333333)
>>> from shapely.geos import geos_version_string
>>> print(geos_version_string)
3.8.0-CAPI-1.13.1
```
If anyone is able to reproduce the behavior, please note that here, otherwise I may close this issue soon.

**Comment by elrapha** [comment] 2020-07-23 11:21
My shapely version is shapely==1.6.4.post2
@mwtoews  What do you mean the nearest coordinate in Cartesian space?

**Comment by mwtoews** [comment] 2020-07-23 21:32
@elrapha Cartesian space means the units of length are the same in all dimensions, e.g. Eastings/Northings, but not Lat/Long. But again, the example that you've provided appears to demonstrate expected behaviour, and does not appear to be related to this issue.

Further testing on Linux shows that this is only an issue with GEOS<=3.7.3. It is not an issue with GEOS>=3.8.0.

Closing this issue since this was an upstream bug. Anyone affected by issue this is advised to upgrade to GEOS 3.8.0 or later.

**Closed by mwtoews** 2020-07-23 21:32 UTC
Labels: geos, upstream bug
