### ISSUE TITLE
MultiPoint constructor drops z coords

### ISSUE THREAD

**Issue by duncanwp** [Toblerity/Shapely#437] opened 2016-12-02 18:40 UTC
I've noticed that when trying to create a MultiPoint instance with numpy arrays the z array gets ignored for some operations such as intersections.

I think the problem is that constructor doesn't properly register the z coordinates when creating in the pointers to the numpy arrays - the points seems to get properly created when passing a Python list but there is obviously a big performance hit for lots of points.

I think this demonstrates the problem:
```
import numpy as np
from shapely.geometry import MultiPoint

pts = np.vstack([np.arange(20)*0.1, np.arange(20)*0.2, np.arange(20)])
multi_point = MultiPoint(pts.T)

print(multi_point.has_z)  # False

multi_point = MultiPoint(pts.T.tolist())

print(multi_point.has_z)  # True
```

**Comment by snorfalorpagus** [comment] 2016-12-02 21:13
I can reproduce this.

It doesn't seem to be an issue with lists.

```
>>> MultiPoint([[0,1,2],[3,4,5]]).wkt
'MULTIPOINT Z (0 1 2, 3 4 5)'
```

**Comment by snorfalorpagus** [comment] 2016-12-03 00:23
I've found the problem. There is an assumption in `geos_multipoint_from_py` that the length of the coordinate sequence for each point is only 2 in length, where it should be N == 2 or 3. I'll submit a PR to fix.

**Comment by snorfalorpagus** [comment] 2016-12-03 00:31
@sgillies This bug goes back at least as far as Shapely 1.2. Are we still supporting that version? There hasn't been a commit in 3 years. Which branch should I aim the patch at?

**Comment by duncanwp** [comment] 2016-12-03 09:57
That was quick! Thanks

**Comment by sgillies** [comment] 2016-12-03 11:07
@snorfalorpagus maint-1.6 please. I think I made this branch too soon, to be honest. I'll take care of merging from there to master.

**Comment by snorfalorpagus** [comment] 2016-12-03 15:38
Ah. It looks like this is already fixed in `maint-1.6` with a different approach.

**Comment by sgillies** [comment] 2016-12-03 16:25
@snorfalorpagus thanks for checking. Do you have any strong desire to continue with the 1.5.x branch? We're so close with 1.6 and users should be able to move straight over.

**Comment by snorfalorpagus** [comment] 2016-12-03 16:32
I don't personally have any need for the 1.5 branch. Do we need to update the README? It suggests that 1.2 and 1.4 are still maintained.

**Closed** 2016-12-06 20:46 UTC
Labels: bug
