### ISSUE TITLE
Install of 1.5.4 fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by selimnairb** [Toblerity/Shapely#231] opened 2015-01-20 02:28 UTC
I get the follow error when installing 1.5.4, which I do not get when running 1.5.3:
```
byte-compiling /usr/local/lib/python2.7/dist-packages/shapely/wkt.py to wkt.pyc

running install_data

error: can't copy 'shapely/_geos.pxi': doesn't exist or not a regular file

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/shapely/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-jY7z2c-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/shapely
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 46: ordinal not in range(128)
```

**Comment by sgillies** [comment] 2015-01-20 03:57
@selimnairb I wonder if there's something else going on, because the difference between 1.5.4 and 1.5.3 is just this:

```diff
diff --git a/shapely/geos.py b/shapely/geos.py
index 5db949f..970a944 100644
--- a/shapely/geos.py
+++ b/shapely/geos.py
@@ -62,7 +62,7 @@ if sys.platform.startswith('linux'):
 elif sys.platform == 'darwin':
     # First test to see if this is a delocated wheel with a GEOS dylib.
     geos_whl_dylib = os.path.abspath(
-            os.path.join(os.path.dirname(__file__), '.dylibs/GEOS'))
+            os.path.join(os.path.dirname(__file__), '.dylibs/libgeos_c.1.dylib'))
     if os.path.exists(geos_whl_dylib):
         _lgeos = CDLL(geos_whl_dylib)
     else:
(END)
```

In the Python issue tracker I found a possibly related [issue 19286](http://bugs.python.org/issue19286) which was fixed in 2.7.7. Is it possible that you successfully installed 1.5.3 using a Python >= 2.7.7 and have a Python < 2.7.7 in the case above?

At any rate, I'll see if more careful specification of package_data or a stricter MANIFEST for a future release will help.

**Comment by jayvdb** [comment] 2015-01-20 03:57
Similar problem with it as a dependency (also on 14.04):

```
libhxl-python$ python setup.py test
running test
Searching for shapely
Reading https://pypi.python.org/simple/shapely/
Best match: Shapely 1.5.4
Downloading https://pypi.python.org/packages/source/S/Shapely/Shapely-1.5.4.tar.gz#md5=5e510df5f26fd5e1bd899ef46ba0f3eb
Processing Shapely-1.5.4.tar.gz
Writing /tmp/easy_install-JHk02A/Shapely-1.5.4/setup.cfg
Running Shapely-1.5.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-JHk02A/Shapely-1.5.4/egg-dist-tmp-iVQPkz
Numpy or Cython not available, shapely.vectorized submodule not being built.
shapely/speedups/_speedups.c:236:20: fatal error: geos_c.h: No such file or directory
 #include "geos_c.h"
                    ^
compilation terminated.
command 'i686-linux-gnu-gcc' failed with exit status 1
Warning: The C extension could not be compiled, speedups are not enabled.
Failure information, if any, is above.
I'm retrying the build without the C extension now.
error: Setup script exited with error: can't copy 'shapely/_geos.pxi': doesn't exist or not a regular file
```

**Comment by jayvdb** [comment] 2015-01-20 03:59
Sorry .. should have included:
```
$ python --version
Python 2.7.6
$ which python
/usr/bin/python
```

**Comment by sgillies** [comment] 2015-01-20 04:02
Yes, looks like Shapely is stumbling (since 1.5.3) into that Python bug I mentioned above. I'm pretty sure 1.5.3 wouldn't install with Python < 2.7.7 either. I think I can work around.

**Comment by sgillies** [comment] 2015-01-20 04:21
@selimnairb @jayvdb would either of you be willing to try `pip install git+https://github.com/Toblerity/Shapely.git@maint#egg=Shapely` for me to see if https://github.com/Toblerity/Shapely/commit/6acdf835d59d2e39c9c09edf7a80d8dc010fb9b5 helps?

**Comment by jayvdb** [comment] 2015-01-20 04:31
Seems to go well, finding geos_c, then

```
Warning: The C extension could not be compiled, speedups are not enabled.

Failure information, if any, is above.

I'm retrying the build without the C extension now.

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip_build_root/Shapely/setup.py", line 298, in <module>

    if 'build_ext' in cmd_classes:

NameError: name 'cmd_classes' is not defined
```

**Comment by sgillies** [comment] 2015-01-20 04:41
@jayvdb thanks, I think 65aee30 might do the trick if you could try one more time.

**Comment by jayvdb** [comment] 2015-01-20 04:42
yup; was just coming to report that worked.

**Comment by reece** [comment] 2015-01-20 05:43
65aee30 works for me too. Python 3.4.2, Ubuntu 14.10, geos 3.4.2-5 (from ubuntu). Thanks!

**Comment by glance-** [comment] 2015-01-20 08:58
My diagnosis why install of Shapely-1.5.4.tar.gz fails to install is that shapely/_geos.pxi is excluded from the tar.gz.

If i re-add that one from the 1.5.3 the package installs again.

Also due to the dependency on it as a data-file, the whole install of the package fails, not just the compilation of the speedups.

**Comment by glance-** [comment] 2015-01-20 09:10
To detect such regressions, one way would be to actually generate a sdist in the travis-run and install that package, to make sure its installable.

**Comment by glance-** [comment] 2015-01-20 10:00
Chokay. Kill the https://github.com/Toblerity/Shapely/blob/maint/setup.py#L162 data_files reference to shapely/_geos.pxi , and then the package becomes installable again.

Still, shapely/vectorized/_vectorized.pyx is shipped in the sdist, so if you have cython installed, that module will fail, due to the missing shapely/_geos.pxi

I don't really understand why the pyx and pxi have bin excluded. Its great that the setup.py script "cythons" the files and ships .c so you can install the package when you don't have cython installed, but when you have cython installed, why shoudn't the c-files be re-generated?

**Comment by sgillies** [comment] 2015-01-20 14:51
I've tagged 1.5.5 and uploads are on PyPI... now.

**Comment by glance-** [comment] 2015-01-20 15:34
You missed my comment above, 1.5.5 still doesn't install:
....
```
byte-compiling /home/anton/Downloads/venv/lib/python2.7/site-packages/shapely/ctypes_declarations.py to ctypes_declarations.pyc

running install_data

creating /home/anton/Downloads/venv/shapely

error: can't copy 'shapely/_geos.pxi': doesn't exist or not a regular file

----------------------------------------
Cleaning up...
Command /home/anton/Downloads/venv/bin/python2 -c "import setuptools, tokenize;__file__='/home/anton/Downloads/venv/build/Shapely/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-w9XYRV-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/anton/Downloads/venv/include/site/python2.7 failed with error code 1 in /home/anton/Downloads/venv/build/Shapely
Traceback (most recent call last):
  File "venv/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/anton/Downloads/venv/local/lib/python2.7/site-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/home/anton/Downloads/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 46: ordinal not in range(128)
```

**Comment by sgillies** [comment] 2015-01-20 15:57
@glance- you're right, I made myself a new virtualenv and the 1.5.5 sdist is broken. I don't know what the hell is going on with shapely/_geos.pxi here. Commencing to dig.

**Comment by glance-** [comment] 2015-01-20 16:25
As i said above:
"Kill the https://github.com/Toblerity/Shapely/blob/maint/setup.py#L162 data_files reference to shapely/_geos.pxi , and then the package becomes installable again."

**Comment by sgillies** [comment] 2015-01-20 16:33
Maybe... hey @pelson did you make _geos.pxi a data file for a specific reason in https://github.com/Toblerity/Shapely/commit/64e79f5ac7801607c76c200402213787c987b050?

**Comment by sgillies** [comment] 2015-01-20 17:14
New 1.5.5 sdists have been uploaded.

**Comment by glance-** [comment] 2015-01-21 10:05
Not my recommended solution, but hey, it works. Thanks!

**Closed** 2015-02-02 21:25 UTC
