### ISSUE TITLE
ops.split() does not split LineString self-intersections as expected

### ISSUE THREAD

**Issue by unwitten** [Toblerity/Shapely#773] opened 2019-09-11 05:19 UTC
## Expected behavior and actual behavior.

When trying to split a LineString that self-intersects, EG:
```python
"""
          (1,2)--<--(2,2)
            |         |
            v         ^
            |         |
(0,1)--->---+--->---(2,1)
            |
            v
            |
          (1,0)
"""
```
If the "splitter" is a point placed at the line self-intersection (1,1), I would expect the line to be split twice at that location, EG from the example above:
```python
from shapely import ops
from shapely.geometry import LineString, Point
line = LineString([(0, 1), (2, 1), (2, 2), (1, 2), (1, 0)])
point = Point(1, 1)
split_line_collection = ops.split(line, point)
```

I would expect the returned geometry collection to contain the following lines:
```python
LineString([(0, 1), (1, 1)])
LineString([(1, 1), (2, 1), (2, 2), (1, 2), (1, 1)])
LineString([(1, 1), (1, 0)])
```

However, it appears in this case to only be splitting the line once by the point, at the "first" instance along the line:
```python
from shapely import ops
from shapely.geometry import LineString, Point
line = LineString([(0, 1), (2, 1), (2, 2), (1, 2), (1, 0)])
point = Point(1, 1)
split_line_collection = ops.split(line, point)
for geom in split_line_collection.geoms:
    print(list(geom.coords))

[(0.0, 1.0), (1.0, 1.0)]
[(1.0, 1.0), (2.0, 1.0), (2.0, 2.0), (1.0, 2.0), (1.0, 0.0)]
```

## Operating system

Windows 10

## Shapely version and provenance

Shapely version 1.6.4, installed using pip

**Comment by sgillies** [comment] 2019-09-11 14:09
Sorry, but this is nearly a duplicate of other closed issues: lines cannot be reliably split using a point due to floating point precision issues.

**Closed by sgillies** 2019-09-11 14:09 UTC
Labels: wontfix

**Comment by unwitten** [comment] 2019-09-11 22:03
Yeah ok, that makes sense.
Sorry for duplicating a closed issue, and thanks for the reply!
