### ISSUE TITLE
Potential slow down for new version of Shapely and GEOS

### ISSUE THREAD

**Issue by DustOfStar** [Toblerity/Shapely#834] opened 2020-02-06 03:17 UTC
Hi,

I am working on a project which involve dissolving multiple polygons together then add a 1m buffer to the dissolved polygon. I use a combination of GeoPandas and Shapely. The code is below:

`Polygon_dissolved = Polygons_gdf.dissolve(by = 'DissolveID', aggfunc='first')`
`Polygon_buffer = Polygon_dissolved.geometry.buffer(distance = 1)`
The code is working, approximate time for **dissolve = 1150** s, approximate time for **buffer = 40 s**.

A few days ago, I install a new environment to my Anaconda with the **same libraries** as before. Then I run the **same program**. This time, approximate time for **dissolve = 300 s,** and approximate time for **buffer = 25000 s** (about 7 hours).

I tried uninstall / reinstall Python 3.7 and Anaconda, and the problem is still there.
I tried running same script and data with other machine (with old environment), and problem solved.
However, I find out that if I download **older** version of libraries to my Anaconda environment, problem **solved.** Therefore, I suspect there are some bugs with current version of either Shapely or GEOS. Maybe the connection between Shapely and GEOS is not stable?

Below I provide the code I used for creating new environment:
`conda create --name gis -c conda-forge python=3.6 jupyter geopandas rasterio rasterstats folium numba scikit-image scikit-learn statsmodels xlrd openpyxl dbfread gdal shapely anaconda spyder descartes`

This is the old environment configuration file: (from Anaconda it's .yml file)
[gis.txt](https://github.com/Toblerity/Shapely/files/4163014/gis.txt)
Inside this file, the key informations are:
- gdal=2.3.3=py36hdf43c64_0
- geopandas=0.4.0=py_1
- geos=3.7.1
- pandas=0.24.0=py36h6538335_0
- shapely=1.6.4=py36h8921fb9_1002

By using old environment, my problem is solved currently. 
Here I recommand to check for potential issue.
Sorry I only provide limited information here.

Best regards

**Comment by DustOfStar** [comment] 2020-02-06 03:24
As supplementary material, I export and import environment by using below methods:
`conda env export > environment.yml`
`conda env create -f environment.yml`

I download python 3.7.6 here:
https://www.python.org/downloads/windows/

and I download Anaconda 2019.10 for Python 3.7 and x64 here:
https://www.anaconda.com/distribution/

**Comment by jorisvandenbossche** [comment] 2020-02-06 07:41
@DustOfStart can you try to provide a minimal, reproducible example? 
For example, try to get a small subset of your data that reproduces the problem (also shows a slowdown). Or if you can't share a part of your data, do you also see the problem with other data that you can share? (eg taking the buffer of some random points).

Secondly, can you check the geos and shapely version in both new and old environment? (I think what you listed above is only for the old?)

**Comment by DustOfStar** [comment] 2020-02-06 20:29
Hi, here is my test script and results:
[Slowdown_test.txt](https://github.com/Toblerity/Shapely/files/4167564/Slowdown_test.txt)

![code](https://user-images.githubusercontent.com/58020598/73975554-710df800-48db-11ea-9ada-bc31667dbc04.png)

And this is result for newer version of environment: The last time is buffer from gpd.geometry
![NewEnv](https://user-images.githubusercontent.com/58020598/73975586-7ff4aa80-48db-11ea-8658-6ad5a84248c9.png)

This is result of older version of environment using same script: The last time is buffer from gpd.geometry
![OldEnv](https://user-images.githubusercontent.com/58020598/73975609-8daa3000-48db-11ea-8b17-a83ff911b682.png)

As mentioned above, the package information of old environment is:

- gdal=2.3.3=py36hdf43c64_0
- geopandas=0.4.0=py_1
- geos=3.7.1
- pandas=0.24.0=py36h6538335_0
- shapely=1.6.4=py36h8921fb9_1002

In comparison, the information of new environment is:
- gdal=3.0.4=py37h2fee047_0
- geopandas=0.6.2=py_0
- geos=3.8.0=he025d50_0
- pandas=1.0.1=py37he350917_0
- shapely=1.7.0=py37h2130f3d_0

**Comment by sgillies** [comment] 2020-02-21 00:20
@DustOfStar thank you for the report. I think this is very related to #847. You see a slowdown with GEOS 3.8.0 compared to 3.7.1 and are using conda, not the wheels I've put on PyPI. This suggests that the cause is in GEOS 3.8.0, not in Shapely.

I'm going to close this ticket and we'll continue in #847.

**Closed by sgillies** 2020-02-21 00:20 UTC

**Comment by jorisvandenbossche** [comment] 2020-02-21 09:25
So here I actually see a slowdown (as opposed in #847) in my environments (conda-forge on linux).

Using this simplified script (only using shapely):

```
import math
import shapely
import shapely.geometry
import shapely.ops

timelist = list(range(1,10000))
PolygonList = []

for t in timelist:
    x = 100000*math.sin(t)
    y = 100000*math.sin(4*t)

    OnePoint   = shapely.geometry.Point(x, y)
    OnePolygon = OnePoint.buffer(distance = 200, resolution = 32)
    PolygonList.append(OnePolygon)

# do unary union with shapely  
UnionResult = shapely.ops.unary_union(PolygonList)

# buffer with shapely result
Polgyon_bfr = UnionResult.buffer(distance = 1)
```

I get the following timings.

Shapely 1.6.4, GEOS 3.7.2:

```
In [2]: %timeit shapely.ops.unary_union(PolygonList)
1.27 s ± 20.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [3]: %timeit UnionResult.buffer(distance = 1)
77.6 ms ± 888 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Shapely 1.7.0, GEOS 3.8.0

```
In [4]: %timeit shapely.ops.unary_union(PolygonList) 
2.4 s ± 430 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [5]: %timeit UnionResult.buffer(distance = 1)
3.79 s ± 497 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

So especially the buffer is much slower. This might be something to report to GEOS?

(and I verified that the resulting MultiPolygon (`UnionResult`) in both cases is equal: at least when dumping to WKB and loading in the other environment, the `equals` method gives True)
