### ISSUE TITLE
Prepared contains differs from normal contains

### ISSUE THREAD

**Issue by mrocklin** [Toblerity/Shapely#519] opened 2017-09-06 13:23 UTC
This fails.  I don't think it should.  I could be mistaken though.

```python
from shapely.geometry import Point, Polygon
import shapely.prepared

point = Point(0.95, 0.05)
geom = Polygon([(0, 0), (1, 0), (0, 1), (0, 0)])

assert shapely.prepared.prep(geom).contains(point) == geom.contains(point)
```

```python
>>> shapely.__version__
'1.6b4'
```

I'm on linux.  I've installed Shapely from conda-forge.

**Comment by ocefpaf** [comment] 2017-09-06 13:29
> I'm on linux. I've installed Shapely from conda-forge

We (`conda-forge`) never packaged `'1.6b4'` :confused:

**Comment by mrocklin** [comment] 2017-09-06 13:31
Well then, I've probably source installed?

**Comment by mrocklin** [comment] 2017-09-06 13:32
Sorry, 1.5.17post1

```python
In [1]: import shapely

In [2]: shapely.__version__
Out[2]: '1.5.17.post1'

In [3]: from shapely.geometry import Point, Polygon
   ...: import shapely.prepared
   ...: 
   ...: point = Point(0.95, 0.05)
   ...: geom = Polygon([(0, 0), (1, 0), (0, 1), (0, 0)])
   ...: 
   ...: assert shapely.prepared.prep(geom).contains(point) == geom.contains(point)
   ...: 
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-3-91a2da531b6f> in <module>()
      5 geom = Polygon([(0, 0), (1, 0), (0, 1), (0, 0)])
      6 
----> 7 assert shapely.prepared.prep(geom).contains(point) == geom.contains(point)

AssertionError: 
```

**Comment by snorfalorpagus** [comment] 2017-09-06 14:03
I can reproduce this. Perhaps this is a bug in GEOS?

**Comment by mrocklin** [comment] 2017-09-06 14:05
Yes, I'm seeing the same thing when I bypass Shapely and go straight to the GEOS C-api in Cython.

**Comment by ocefpaf** [comment] 2017-09-06 14:37
FYI I just add https://github.com/Toblerity/Shapely/issues/519#issuecomment-327484168 as a test to the `shapely` feedstock and built with `geos 3.6.0`, `3.6.1`, and `3.6.2` and they all fail :unamused:

**Comment by sgillies** [comment] 2017-09-06 16:00
I distribute GEOS 3.4.2 with the shapely wheels that I put on PyPI and can't reproduce the issue with that older version.

**Comment by mrocklin** [comment] 2017-09-06 16:03
My error was on 3.5.1
```
(geopandas) mrocklin@carbon:~$ conda list | grep geos
geos                      3.5.1                         1    conda-forge
```

**Comment by sgillies** [comment] 2017-09-06 16:20
I've created a ticket upstream: https://trac.osgeo.org/geos/ticket/841. @mrocklin @snorfalorpagus can you confirm that I reported correctly?

**Comment by ocefpaf** [comment] 2017-09-06 16:31
`geos 3.4.2` works for the conda package too. But we cannot afford to downgrade to that version :unamused:

**Comment by mrocklin** [comment] 2017-09-06 16:37
Looks good to me.  Thanks for going through the effort of raising upstream @sgillies

**Comment by sgillies** [comment] 2017-09-06 19:20
This seems to be a wontfix and I've closed the upstream issue. Strictly speaking, the point is on the boundary of the polygon and thus is *not* contained. Due to numerical precision issues, it may be computed to not be on the boundary, and that's what I see in my test. Something has changed since 3.4.2, but the results are actually more correct for one of the polygons. I didn't note above whether it was `prep(geom).contains(point)` or `geom.contains(point)` that was `False` with GEOS 3.5.1.

**Closed** 2017-10-25 03:28 UTC
Labels: geos, upstream bug
